app:
  name: software-engineering-git-experiment
  version: 1.0.0
  description: A simple project for Git branch management practice

author:
  name: "陈翔"
  student_id: "2314035"

runtime:
  language: Python
  version: "3.12"

git:
  initial_branch: B1
  parallel_branches:
    - B2
    - B3
c4_change: true
